esphome:
  name: garden_sprinkler
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_pass
  manual_ip:
    # Set this to the IP of the ESP
    static_ip: x.x.x.x
    # Set this to the IP address of the router. Often ends with .1
    gateway: x.x.x.1
    # The subnet of the network. 255.255.255.0 works for most home networks.
    subnet: 255.255.255.0

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  #ap:
  #  ssid: "Garden Sprinkler"
  #  password: "ZSaC3N9QOJiK"

#captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

web_server:
  port: 80

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: "Garden Sprinkler Switch Button"
    on_press:
      - switch.toggle: relay

switch:
  - platform: gpio
    name: "Garden Sprinkler Switch Relay"
    pin: GPIO12
    id: relay

status_led:
  pin:
    number: GPIO13
    inverted: yes
